# Generated by Django 5.0.4 on 2024-04-20 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='second_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Academica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, choices=[('CESMAG', 'Universidad Cesmag'), ('UDENAR', 'Universidad de Nariño'), ('UNIMAR', 'Universidad Mariana'), ('UCC', 'Universidad Coperativa de Colombia'), ('UNAD', 'Universidad Nacional Abierta y a Distancia'), ('UAN', 'Universidad Antonio Nariño'), ('SENA', 'Servicio Nacional de Aprendizaje')], max_length=50, null=True, verbose_name='Universidad')),
                ('rol', models.CharField(blank=True, choices=[('PROFESOR', 'Profesor'), ('ESTUDIANTE', 'Estudiante')], max_length=50, null=True, verbose_name='Rol')),
                ('profession', models.CharField(blank=True, choices=[('Ing. Sistemas', 'Ingeniero de Sistemas'), ('Ing. Electrónica', 'Ingeniero Electrónico'), ('Tecnología en sistemas', 'Tecnología en Sistemas')], max_length=150, null=True, verbose_name='Carrera profesional')),
                ('semester', models.IntegerField(blank=True, choices=[('I', 1), ('II', 2), ('III', 4), ('V', 5), ('VI', 6), ('VII', 7), ('VIII', 8), ('IX', 9), ('X', 10)], null=True, verbose_name='semestre')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Academica',
                'verbose_name_plural': 'Academicas',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='no_picture.jpg', upload_to='avatars')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, 'Hombre'), (2, 'Mujer')], null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='número de teléfono')),
                ('slug', models.SlugField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
