# Generated by Django 5.0.4 on 2024-04-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='second_name',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
