# Generated by Django 5.0.4 on 2024-04-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_second_last_name_customuser_second_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academica',
            name='rol',
            field=models.CharField(choices=[('PROFESOR', 'Profesor'), ('ESTUDIANTE', 'Estudiante')], default='ESTUDIANTE', max_length=50, verbose_name='Rol'),
        ),
    ]
