# Generated by Django 5.0.4 on 2024-04-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser_second_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='second_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
