# Generated by Django 5.0.4 on 2024-04-24 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_academica_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academica',
            name='rol',
            field=models.CharField(choices=[('PROFESOR', 'Profesor'), ('ESTUDIANTE', 'Estudiante')], max_length=50, verbose_name='Rol'),
        ),
    ]
