# Generated by Django 5.0.4 on 2024-04-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_academica_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academica',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V'), (6, 'VI'), (7, 'VII'), (8, 'VIII'), (9, 'IX'), (10, 'X')], null=True, verbose_name='semestre'),
        ),
    ]
