# Generated by Django 5.0.4 on 2024-04-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Hombre'), (2, 'Mujer')], default=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Universidad Cesmag'), (2, 'Universidad de Nariño'), (3, 'Universidad Mariana'), (4, 'Universidad Coperativa de Colombia'), (5, 'Universidad Nacional Abierta y a Distancia'), (6, 'Universidad Antonio Nariño'), (7, 'Servicio Nacional de Aprendizaje')], default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Estudiante'), (2, 'Profesor')], default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession_career',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ingeniero de Sistemas'), (2, 'Ingeniero Electrónico'), (3, 'Tecnología en Sistemas')], default=1),
        ),
    ]
