# Generated by Django 5.0.4 on 2024-04-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_gender_profile_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(2, 'Hombre'), (3, 'Mujer')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='institution',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Universidad Cesmag'), (2, 'Universidad de Nariño'), (3, 'Universidad Mariana'), (4, 'Universidad Coperativa de Colombia'), (5, 'Universidad Nacional Abierta y a Distancia'), (6, 'Universidad Antonio Nariño'), (7, 'Servicio Nacional de Aprendizaje')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Estudiante'), (2, 'Profesor')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession_career',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Ingeniero de Sistemas'), (2, 'Ingeniero Electrónico'), (3, 'Tecnología en Sistemas')], null=True),
        ),
    ]
