# Generated by Django 5.0.4 on 2024-05-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_academica_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academica',
            name='profession',
            field=models.CharField(blank=True, choices=[('Ingeniero de Sistemas', 'Ingenieria De Sistemas'), ('Ingeniero Electrónico', 'Ingenieria Electronica'), ('Tecnología en Sistemas', 'Tecnologia En Sistemas')], max_length=150, null=True, verbose_name='Carrera profesional'),
        ),
    ]
