# Generated by Django 5.0.4 on 2024-04-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_profile_gender_alter_profile_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Hombre'), (2, 'Mujer')], null=True),
        ),
    ]
