# Generated by Django 5.0.4 on 2024-04-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='second_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, 'Hombre'), (2, 'Mujer')], default=1),
        ),
    ]
