# Generated by Django 5.0.4 on 2024-04-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='occupation',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Estudiante'), (2, 'Profesor')], default=1),
        ),
    ]
