# Generated by Django 5.0.4 on 2024-04-25 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requeriment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('version', models.CharField(max_length=50, verbose_name='versión')),
                ('priority', models.PositiveBigIntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')], max_length=50, verbose_name='prioridad')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Requeriment',
                'verbose_name_plural': 'Requeriments',
            },
        ),
        migrations.CreateModel(
            name='Funtionality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('requeriment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.requeriment', verbose_name='requeriment')),
            ],
            options={
                'verbose_name': 'Funtionality',
                'verbose_name_plural': 'Funtionalities',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Software titulo')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('version', models.CharField(max_length=50, verbose_name='version')),
                ('slug', models.SlugField()),
                ('date_created', models.DateField(verbose_name='Fecha de creación')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='logo')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
            },
        ),
        migrations.AddField(
            model_name='requeriment',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.software', verbose_name='software'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_software', models.PositiveSmallIntegerField(choices=[(1, 'Software de aplicación'), (2, 'Software de programación'), (3, 'Software de sistema')], default=1, verbose_name='Tipo de software por funcionalidad')),
                ('type_public', models.PositiveSmallIntegerField(choices=[(1, 'Apto para todo público'), (2, 'Adolecentes'), (3, 'Mayores de 17 años')], default=1, verbose_name='Tipo de audiencia')),
                ('type_industry', models.PositiveSmallIntegerField(choices=[(1, 'Salud'), (2, 'Educación'), (3, 'Finanzas')], verbose_name='sector')),
                ('os', models.CharField(max_length=250, verbose_name='sistema operativo')),
                ('software', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.software', verbose_name='software')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
