# Generated by Django 5.0.4 on 2024-08-22 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requeriment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='titulo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='uploads')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='uploads')),
                ('version', models.CharField(max_length=50, verbose_name='versión')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Requeriment',
                'verbose_name_plural': 'Requeriments',
            },
        ),
        migrations.CreateModel(
            name='Funtionality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('requeriment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.requeriment', verbose_name='requeriment')),
            ],
            options={
                'verbose_name': 'Funtionality',
                'verbose_name_plural': 'Funtionalities',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Software titulo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('version', models.CharField(max_length=50, verbose_name='version')),
                ('slug', models.SlugField()),
                ('date_created', models.DateField(blank=True, null=True, verbose_name='Fecha de creación')),
                ('type_of_work', models.CharField(choices=[('Software Inedito', 'Software Inedito'), ('Software Derivado', 'Software Derivado')], default='Software Derivado', max_length=50, verbose_name='El software es')),
                ('origin_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='nacionalidad')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Softwares',
            },
        ),
        migrations.AddField(
            model_name='requeriment',
            name='software',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.software', verbose_name='software'),
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=150, verbose_name='plataforma')),
                ('os', models.CharField(blank=True, max_length=250, null=True, verbose_name='sistema operativo')),
                ('procesador', models.CharField(blank=True, max_length=250, null=True, verbose_name='sistema operativo')),
                ('ram', models.CharField(blank=True, max_length=250, null=True, verbose_name='sistema operativo')),
                ('storage', models.CharField(blank=True, max_length=250, null=True, verbose_name='sistema operativo')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.software', verbose_name='software')),
            ],
            options={
                'verbose_name': 'Installation',
                'verbose_name_plural': 'Installations',
            },
        ),
        migrations.CreateModel(
            name='CopyrightCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.software', verbose_name='software')),
            ],
            options={
                'verbose_name': 'CopyrightCertificate',
                'verbose_name_plural': 'CopyrightCertificates',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(blank=True, max_length=150, null=True, verbose_name='tipo de licencia')),
                ('type_software', models.CharField(blank=True, choices=[('Software de productividad ayuda a los usuarios a realizar tareas comunes de manera más eficiente.', 'Productividad'), ('Software de creatividad ayuda a los usuarios a crear contenido multimedia, como imágenes, videos y música.', 'Creatividad'), ('El software de comunicación ayuda a los usuarios a comunicarse con otros.', 'Comunicacion'), ('El software empresarial ayuda a las empresas a realizar sus operaciones.', 'Negocios'), ('El software de programación ayuda a los desarrolladores a crear distintas aplicaciones.', 'Programacion'), ('El software de entretenimiento ayuda a los usuarios a relajarse y divertirse.', 'Entretenimiento'), ('El software educativo ayuda a los usuarios a aprender cosas nuevas.', 'Educacion'), ('El software de bienestar se enfoca en el cuidado de la salud de los usuarios.', 'Bienestar Y Salud')], max_length=150, null=True, verbose_name='Tipo de software')),
                ('tasks', models.TextField(blank=True, max_length=255, null=True, verbose_name='tareas')),
                ('type_public', models.CharField(choices=[('Apto para todo público', 'Apto Para Todo Publico'), ('Adolecentes', 'Adolescentes'), ('Mayores de 17 años', 'Mayores De 17 Años')], default='Apto para todo público', max_length=100, verbose_name='Tipo de audiencia')),
                ('level_public', models.CharField(choices=[('Usuarios con poco o ningún conocimiento previo sobre el software o el tipo de tecnología relacionada.', 'Principiante'), ('Usuarios con conocimiento básico del software o la tecnología relacionada y puede realizar tareas básicas.', 'Intermedio'), ('Usuarios con conocimiento profundo del software o la tecnología relacionada y puede realizar tareas complejas.', 'Experto')], default='Usuarios con poco o ningún conocimiento previo sobre el software o el tipo de tecnología relacionada.', max_length=200, verbose_name='Nivel de conocimiento')),
                ('type_industry', models.CharField(blank=True, choices=[('Salud', 'Salud'), ('Educación', 'Educacion'), ('Finanzas y economia', 'Finanzas Y Economia'), ('Manufactura', 'Manufactura'), ('Transporte y logistica', 'Transporte Y Logistica'), ('Agricultura', 'Agricultura'), ('Gobierno', 'Gobierno'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Energía', 'Energia'), ('Recursos Humanos', 'Recursos Humanos'), ('Marketing', 'Marketing'), ('Legal', 'Legal'), ('Construcción', 'Construccion'), ('Turismo', 'Turismo'), ('Bienes Raíces', 'Bienes Raices'), ('Entretenimiento', 'Entretenimiento'), ('Deportes', 'Deportes'), ('Ciencia e investigación', 'Ciencia E Investigacion'), ('Servicios Publicos', 'Servicios Publicos'), ('Desarrollo de Software', 'Software')], max_length=200, null=True, verbose_name='sector')),
                ('slug', models.SlugField()),
                ('software', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.software', verbose_name='software')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Primer Nombre')),
                ('second_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Segundo Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('type_ID', models.CharField(max_length=50, verbose_name='Tipo de Documento')),
                ('num_ID', models.CharField(max_length=50, verbose_name='Numero de Documento')),
                ('born_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('nacionality', models.CharField(default='COLOMBIA', max_length=50, verbose_name='Nacionalidad')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.software', verbose_name='software')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Arquitect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('description', models.CharField(max_length=250, verbose_name='descripcion')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('software', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.software', verbose_name='software')),
            ],
            options={
                'verbose_name': 'Arquitect',
                'verbose_name_plural': 'Arquitects',
            },
        ),
    ]
