# Generated by Django 5.0.4 on 2024-10-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='screen',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='resolución de pantalla'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='storage',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='siste'),
        ),
    ]
