# Generated by Django 5.0.4 on 2024-04-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2023-01-20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='updated_at',
            field=models.DateField(auto_now_add=True, default='2023-01-20'),
            preserve_default=False,
        ),
    ]
