# Generated by Django 5.0.4 on 2024-04-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='date_created',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de creación'),
        ),
    ]
