# Generated by Django 5.0.4 on 2024-04-10 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2023-01-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='date_created',
            field=models.DateField(default='2023-01-12', verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='software',
            name='origin_country',
            field=models.CharField(default='COL', max_length=50, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='software',
            name='type_of_work',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Obra inédita'), (2, 'Obra derivada')], default=1, verbose_name='El software es'),
        ),
        migrations.AddField(
            model_name='software',
            name='updated_at',
            field=models.DateField(auto_now_add=True, default='2023-01-23'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='software',
            name='license',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Propietario'), (2, 'Libre'), (3, 'Código Abierto')], verbose_name='tipo de licencia'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_software', models.PositiveSmallIntegerField(choices=[(1, 'Software de aplicación'), (2, 'Software de programación'), (3, 'Software de sistema')], default=1, verbose_name='Tipo de software por funcionalidad')),
                ('type_public', models.PositiveSmallIntegerField(choices=[(1, 'Apto para todo público'), (2, 'Adolecentes'), (3, 'Mayores de 17 años')], default=1, verbose_name='Tipo de audiencia')),
                ('type_industry', models.PositiveSmallIntegerField(choices=[(1, 'Salud'), (2, 'Educación'), (3, 'Finanzas')], verbose_name='sector')),
                ('os', models.CharField(max_length=250, verbose_name='sistema operativo')),
                ('software', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.software', verbose_name='software')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Requeriment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='descripción')),
                ('version', models.CharField(max_length=50, verbose_name='versión')),
                ('priority', models.PositiveBigIntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')], max_length=50, verbose_name='prioridad')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.software', verbose_name='software')),
            ],
            options={
                'verbose_name': 'Requeriment',
                'verbose_name_plural': 'Requeriments',
            },
        ),
        migrations.CreateModel(
            name='Funtionality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('requeriment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.requeriment', verbose_name='requeriment')),
            ],
            options={
                'verbose_name': 'Funtionality',
                'verbose_name_plural': 'Funtionalities',
            },
        ),
    ]
