# Generated by Django 5.0.4 on 2024-04-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_alter_software_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='license',
            field=models.TextField(blank=True, choices=[('PROPIETARIO', 'Software propietario'), ('CÓDIGO ABIERTO', 'Software de Código Abierto')], max_length=150, null=True, verbose_name='tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_software',
            field=models.TextField(blank=True, choices=[(1, 'Software de aplicación'), (2, 'Software de programación'), (3, 'Software de sistema')], max_length=150, null=True, verbose_name='Tipo de software por funcionalidad'),
        ),
    ]
