# Generated by Django 5.0.4 on 2024-04-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_software_created_at_software_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeriment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
    ]
