# Generated by Django 5.0.4 on 2024-04-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_software_created_at_software_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='date_created',
            field=models.DateField(default='2024-01-02', verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
    ]
