# Generated by Django 5.0.4 on 2024-04-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_software_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='origin_country',
            field=models.CharField(blank=True, max_length=50, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='software',
            name='type_of_work',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Obra inédita'), (2, 'Obra derivada')], default=1, verbose_name='El software es'),
        ),
    ]
