# Generated by Django 5.0.4 on 2024-04-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_category_license_alter_category_type_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type_industry',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Salud'), (2, 'Educación'), (3, 'Finanzas')], null=True, verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_public',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Apto para todo público'), (2, 'Adolecentes'), (3, 'Mayores de 17 años')], null=True, verbose_name='Tipo de audiencia'),
        ),
    ]
