# Generated by Django 5.0.4 on 2024-04-09 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_software_origin_country_software_type_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='license',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Propietario'), (2, 'Libre'), (3, 'Código Abierto')], verbose_name='tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='software',
            name='origin_country',
            field=models.CharField(default='COL', max_length=50, verbose_name='country'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_software', models.PositiveSmallIntegerField(choices=[(1, 'Software de aplicación'), (2, 'Software de gestión'), (3, 'Software de desarrollo'), (4, 'Software de sistema')], default=1, verbose_name='Tipo de software por funcionalidad')),
                ('type_public', models.PositiveSmallIntegerField(choices=[(1, 'Apto para todo público'), (2, 'Adolecentes'), (3, 'Mayores de 17 años')], verbose_name='Tipo de audiencia')),
                ('collection', models.CharField(blank=True, max_length=250, null=True, verbose_name='categoria')),
                ('os', models.CharField(max_length=250, verbose_name='sistema operativo')),
                ('software', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.software', verbose_name='software')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Requeriment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='descripción')),
                ('version', models.CharField(max_length=50, verbose_name='versión')),
                ('priority', models.PositiveBigIntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')], max_length=50, verbose_name='prioridad')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.software', verbose_name='software')),
            ],
            options={
                'verbose_name': 'Requeriment',
                'verbose_name_plural': 'Requeriments',
            },
        ),
        migrations.CreateModel(
            name='Funtionality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('requeriment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repository.requeriment', verbose_name='requeriment')),
            ],
            options={
                'verbose_name': 'Funtionality',
                'verbose_name_plural': 'Funtionalities',
            },
        ),
    ]
