# Generated by Django 5.0.4 on 2024-04-22 15:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0004_alter_software_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
