# Generated by Django 5.0.4 on 2024-04-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_alter_category_type_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tasks',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='tareas'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_software',
            field=models.TextField(blank=True, choices=[('Productividad', 'Software de productividad'), ('Multimedia', 'Software de multimedia'), ('Juegos', 'Juegos'), ('Internet', 'Internet'), ('Herramientas', 'Herramientas'), ('Herramientas de desarrollo', 'Programming'), ('Lenguaje de programación', 'Lenguage Programming')], max_length=150, null=True, verbose_name='Tipo de software'),
        ),
    ]
