# Generated by Django 5.0.4 on 2024-04-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_alter_software_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='description',
            field=models.CharField(max_length=150, verbose_name='description'),
        ),
    ]
