# Generated by Django 5.0.4 on 2024-04-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_category_tasks_alter_category_type_software'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='origin_country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='nacionalidad'),
        ),
        migrations.AddField(
            model_name='software',
            name='type_of_work',
            field=models.CharField(choices=[('Obra inédita', 'Obra Inedita'), ('Obra derivada', 'Obra Derivada')], default='Obra derivada', max_length=50, verbose_name='El software es'),
        ),
        migrations.AlterField(
            model_name='category',
            name='tasks',
            field=models.CharField(blank=True, choices=[('Gestión de archivos y carpetas', 'Gestion Archivos'), ('Procesadores de texto', 'Procesamiento Textos'), ('Cálculos y análisis de datos', 'Calculos Analisis Datos'), ('Gestión de bases de datos', 'Gestion Bases Datos'), ('Comunicación y colaboración', 'Comunicacion Colaboracion'), ('Reproducción multimedia de audio y video', 'Reproduccion Multimedia'), ('Editor de contenido multimedia', 'Creacion Contenido Multimedia'), ('Juegos', 'Juegos'), ('Navegadores web', 'Navegacion Web'), ('Mensajeria instantanea', 'Navegacion Web Mesangeria'), ('Gestión de dispositivos', 'Gestion Dispositivos'), ('Automatización de tareas', 'Automatizacion Tareas'), ('Seguridad informática', 'Seguridad Informatica'), ('Compresion de archivos', 'Comprension Archivos'), ('Gestión del tiempo', 'Gestion Tiempo'), ('Traducción de idiomas', 'Traduccion Idiomas'), ('Educación y aprendizaje', 'Educacion Aprendizaje'), ('Diseño y modelado', 'Diseño Modelado'), ('Gestión de proyectos', 'Gestion Proyectos'), ('Contabilidad y finanzas', 'Contabilidad Finanzas'), ('Gestión de relaciones con clientes (CRM)', 'Gestion Relaciones Clientes'), ('Business Intelligence (BI)', 'Business Intelligence'), ('E-commerce', 'E Commerce'), ('Mineria de datos', 'Mineria De Datos')], max_length=255, null=True, verbose_name='tareas'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_industry',
            field=models.CharField(blank=True, choices=[('Salud', 'Salud'), ('Educación', 'Educacion'), ('Finanzas', 'Finanzas Y Economia'), ('Manufactura', 'Manufactura'), ('Transporte y logística', 'Transporte Y Logistica'), ('Agricultura', 'Agricultura'), ('Gobierno', 'Gobierno'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Energía', 'Energia'), ('Recursos Humanos', 'Recursos Humanos'), ('Marketing', 'Marketing'), ('Legal', 'Legal'), ('Construcción', 'Construccion'), ('Turismo', 'Turismo'), ('Bienes Raíces', 'Bienes Raices'), ('Entretenimiento', 'Entretenimiento'), ('Deportes', 'Deportes'), ('Ciencia e investigación', 'Ciencia E Investigacion'), ('Servicios Públicos', 'Servicios Publicos')], max_length=100, null=True, verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_public',
            field=models.CharField(choices=[('Apto para todo público', 'Apto Para Todo Publico'), ('Adolecentes', 'Adolescentes'), ('Mayores de 17 años', 'Mayores De 17 Años')], default='Apto para todo público', max_length=100, verbose_name='Tipo de audiencia'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_software',
            field=models.TextField(blank=True, choices=[('Software de productividad', 'Productivity'), ('Software de multimedia', 'Multimedia'), ('Juegos', 'Games'), ('Internet', 'Internet'), ('Herramientas', 'Tools'), ('Herramientas de desarrollo', 'Programacion'), ('Lenguaje de programación', 'Lenguajes De Programacion'), ('Herramientas Devops', 'Devops'), ('Bases de datos', 'Bases De Datos')], max_length=150, null=True, verbose_name='Tipo de software'),
        ),
    ]
