# Generated by Django 5.0.4 on 2024-04-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_category_slug_alter_category_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='license',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='tipo de licencia'),
        ),
        migrations.AlterField(
            model_name='category',
            name='os',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='sistema operativo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_software',
            field=models.CharField(blank=True, choices=[('Software de productividad', 'Productividad'), ('Software de multimedia', 'Multimedia'), ('Juegos', 'Juegos'), ('Internet', 'Internet'), ('Herramientas', 'Herramientas Y Librerias'), ('Herramientas de desarrollo', 'Programacion'), ('Lenguaje de programación', 'Lenguajes De Programacion'), ('Herramientas Devops', 'Devops'), ('Bases de datos', 'Bases De Datos')], max_length=150, null=True, verbose_name='Tipo de software'),
        ),
    ]
