# Generated by Django 5.0.4 on 2024-05-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_alter_category_license_alter_category_os_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='tasks',
            field=models.TextField(blank=True, choices=[('Gestión de archivos y carpetas', 'Gestion Archivos'), ('Procesadores de texto', 'Procesamiento Textos'), ('Cálculos y análisis de datos', 'Calculos Analisis Datos'), ('Gestión de bases de datos', 'Gestion Bases Datos'), ('Comunicación y colaboración', 'Comunicacion Colaboracion'), ('Reproducción multimedia de audio y video', 'Reproduccion Multimedia'), ('Editor de contenido multimedia', 'Creacion Contenido Multimedia'), ('Juegos', 'Juegos'), ('Navegadores web', 'Navegacion Web'), ('Mensajeria instantanea', 'Navegacion Web Mesangeria'), ('Gestión de dispositivos', 'Gestion Dispositivos'), ('Automatización de tareas', 'Automatizacion Tareas'), ('Seguridad informática', 'Seguridad Informatica'), ('Compresion de archivos', 'Comprensor  De Archivos'), ('Gestión del tiempo', 'Gestion Tiempo'), ('Traducción de idiomas', 'Traduccion Idiomas'), ('Educación y aprendizaje', 'Educacion Aprendizaje'), ('Diseño y modelado', 'Diseño Modelado'), ('Gestión de proyectos', 'Gestion Proyectos'), ('Contabilidad y finanzas', 'Contabilidad Finanzas'), ('Gestión de relaciones con clientes (CRM)', 'Gestion Relaciones Clientes'), ('Business Intelligence (BI)', 'Business Intelligence'), ('E-commerce', 'E Commerce'), ('Mineria de datos', 'Mineria De Datos')], max_length=255, null=True, verbose_name='tareas'),
        ),
    ]
