# Generated by Django 5.0.4 on 2024-05-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_alter_category_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requeriment',
            name='priority',
        ),
        migrations.AddField(
            model_name='requeriment',
            name='name',
            field=models.CharField(max_length=50, null='False', verbose_name='titulo'),
            preserve_default='False',
        ),
        migrations.AlterField(
            model_name='category',
            name='tasks',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='tareas'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_industry',
            field=models.CharField(blank=True, choices=[('Salud', 'Salud'), ('Educación', 'Educacion'), ('Finanzas y economia', 'Finanzas Y Economia'), ('Manufactura', 'Manufactura'), ('Transporte y logistica', 'Transporte Y Logistica'), ('Agricultura', 'Agricultura'), ('Gobierno', 'Gobierno'), ('Telecomunicaciones', 'Telecomunicaciones'), ('Energía', 'Energia'), ('Recursos Humanos', 'Recursos Humanos'), ('Marketing', 'Marketing'), ('Legal', 'Legal'), ('Construcción', 'Construccion'), ('Turismo', 'Turismo'), ('Bienes Raíces', 'Bienes Raices'), ('Entretenimiento', 'Entretenimiento'), ('Deportes', 'Deportes'), ('Ciencia e investigación', 'Ciencia E Investigacion'), ('Servicios Publicos', 'Servicios Publicos')], max_length=100, null=True, verbose_name='sector'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_software',
            field=models.CharField(blank=True, choices=[('Software de productividad', 'Productividad'), ('Software de multimedia', 'Multimedia'), ('Juegos', 'Juegos'), ('Internet', 'Internet'), ('Herramientas y librerias', 'Herramientas Y Librerias'), ('Herramientas de desarrollo', 'Programacion'), ('Lenguaje de programación', 'Lenguajes De Programacion'), ('Herramientas Devops', 'Devops'), ('Bases de datos', 'Bases De Datos')], max_length=150, null=True, verbose_name='Tipo de software'),
        ),
        migrations.AlterField(
            model_name='software',
            name='type_of_work',
            field=models.CharField(choices=[('Software Inedito', 'Software Inedito'), ('Software Derivado', 'Software Derivado')], default='Software Derivado', max_length=50, verbose_name='El software es'),
        ),
    ]
