# Generated by Django 5.0.4 on 2024-05-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_remove_requeriment_priority_requeriment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type_public',
            field=models.CharField(choices=[('Apto para todo público', 'Apto Para Todo Publico'), ('Adolecentes', 'Adolescentes'), ('Mayores de 17 años', 'Mayores De 17 Años'), ('Publico Especifico', 'Publico Especifico')], default='Apto para todo público', max_length=100, verbose_name='Tipo de audiencia'),
        ),
        migrations.AlterField(
            model_name='category',
            name='type_software',
            field=models.CharField(blank=True, choices=[(' El software de productividad ayuda a los usuarios a realizar tareas comunes de manera más eficiente.', 'Productividad'), ('El software de creatividad ayuda a los usuarios a crear contenido multimedia, como imágenes, videos y música.', 'Creatividad'), ('El software de comunicación ayuda a los usuarios a comunicarse con otros.', 'Comunicacion'), ('El software empresarial ayuda a las empresas a realizar sus operaciones.', 'Negocios'), ('El software de programación ayuda a los desarrolladores a crear distintas aplicaciones.', 'Programacion'), ('El software de entretenimiento ayuda a los usuarios a relajarse y divertirse.', 'Entretenimiento'), ('El software educativo ayuda a los usuarios a aprender cosas nuevas.', 'Educacion'), ('El software de bienestar se enfoca en el cuidado de la salud de los usuarios.', 'Bienestar Y Salud')], max_length=150, null=True, verbose_name='Tipo de software'),
        ),
        migrations.AlterField(
            model_name='requeriment',
            name='name',
            field=models.CharField(default='2023-01-01', max_length=50, verbose_name='titulo'),
            preserve_default=False,
        ),
    ]
