# Generated by Django 5.0.4 on 2024-05-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0012_alter_category_type_public_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquitect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('description', models.CharField(max_length=250, verbose_name='descripciooon')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Imagen')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Arquitect',
                'verbose_name_plural': 'Arquitects',
            },
        ),
    ]
