# Generated by Django 5.0.4 on 2024-05-10 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_arquitect'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquitect',
            name='software',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='repository.software', verbose_name='software'),
            preserve_default=False,
        ),
    ]
