# Generated by Django 5.0.4 on 2024-05-10 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_arquitect_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquitect',
            name='description',
            field=models.CharField(max_length=250, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='arquitect',
            name='software',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.software', verbose_name='software'),
        ),
    ]
