# Generated by Django 5.0.4 on 2024-05-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0015_alter_arquitect_description_alter_arquitect_software'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
    ]
