# Generated by Django 5.0.4 on 2024-05-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_alter_software_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
    ]
